/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ci.test

class Library {
    fun someLibraryMethod(): Boolean {
        println("hello world")
        return true
    }
}
