/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ci.test

class Library {
    fun evaluate(val value: Int): Boolean {
        if (value < 10) {
          return true
        }
        else if (value % 2 == 0 && value < 20) {
            return true
        }
        else {
            return false
        }
    }
}
